### PR TITLE
Fix method signature as `ModelReaderAndWriter.deserialize` can never return `null`

### PR DESCRIPTION
**Pull request by yassenb**

### CODE REVIEW

**Review by jillesvangurp — COMMENTED** [review]
It can return null if you turn off source on your index or use source filtering.

**Comment by yassenb** [comment]
Not sure what you mean. Can you give an example?
I was going by code alone alone. `T?` is coming from the result of `ModelReaderAndWriter.deserialize` which returns `T`. It used to return `T?` and then it got updated in b35b6d49f134e3a954773fb271d51e27e031bc10 and that's the point where I think this change was missed out

**Comment by jillesvangurp** [comment]
Those are two scenarios where there is nothing to de-serialize because there is no source in the hits.

**Comment by jillesvangurp** [comment]
I will look at this in detail though. It might be possible to do this like you say. We'll need a test for this ideally.

**Comment by yassenb** [comment]
Not sure what "source" would be in the source code. When there are no results this would just be an empty sequence.

Again, looking at it purely from a compiler perspective it's impossible for the second element of the `Pair` to be `null` because it's impossible for `ModelReaderAndWriter.deserialize` to return `null` given its type signature. If anything blows up it will be `ModelReaderAndWriter.deserialize` of further up the stack and it will blow up regardless of the type signature of `hits`.

**Comment by jillesvangurp** [comment]
Added the test now and tested briefly. It seems you are right. Thanks for the pull request.

**Pull request merged**
